[build]
  command = "npm ci && npm run build"
  publish = ".next"
  base = "app"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18.20.8"
  NPM_FLAGS = "--no-optional --no-audit --no-fund"
  CANVAS_SKIP_INSTALLATION = "true"
  SKIP_NATIVE_BUILDS = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
